openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - network_firewall
      - network_label
      properties:
        database_engine:
          title: Database Engine
          type: string
          description: The database engine to use, such as 'mysql' or 'postgres'.
          default: mysql
          x-walrus-ui:
            group: Basic
            order: 1
        database_size:
          title: Database Size
          type: string
          description: The size of the database instance, such as 'g3.k3.small'. It
            supports regex matching.
          default: db.small
          x-walrus-ui:
            group: Basic
            order: 2
        network_label:
          title: Network Label
          type: string
          description: The label of the network to associate with the database instance.
          x-walrus-ui:
            group: Basic
            order: 3
        network_firewall:
          title: Network Firewall
          type: string
          description: The name of the firewall to associate with the database instance.
          x-walrus-ui:
            group: Basic
            order: 4
        database_name:
          title: Database Name
          type: string
          description: The name of the database instance to be created.
          default: custom_database
          x-walrus-ui:
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
